.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WP\-DEPLOY\-PUSH" "1" "" "WP-CLI"
.
.SH "NAME"
\fBwp\-deploy\-push\fR \- Push local to remote
.
.SH "SYNOPSIS"
wp deploy push \fIenvironment\fR \-\-what=\fIwhat\fR
.
.SH "OPTIONS"
.
.TP
\fIenvironment\fR:
.
.IP
The name of the environment\. This is the prefix of the constants defined in wp\-config\.
.
.TP
\fB\-\-what\fR=\fIwhat\fR:
.
.IP
What needs to be pushed\. Suports multiple comma sepparated values\. This determines the order of execution for deployments\. Valid options are: \'db\' (deploys the databse with the url and paths replaced) and \'uploads\' (deploys the uploads folder)\.
.
.SH "EXAMPLES"
.
.nf

# Deploy database and uploads folder
wp deploy staging \-\-what=db,uploads
.
.fi

